import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import Footer from "@/components/footer/Footer";
import Navbar from "@/components/header/Navbar";
import { Toaster } from "@/components/ui/sonner";


export const metadata: Metadata = {
  title: "MYCart Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(`antialiased relative h-full min-h-screen`)}
      >
        <main className="relative flex flex-col min-h-screen">
          <Navbar />
          <div className="flex-1 flex-grow">
            {children}
          </div>
          <Footer />
        </main>
        <Toaster />
      </body>
    </html>
  );
}
